# This value must be set.
SLACK_API_TOKEN: ""

IAM_HOST: ""
IAM_API_TOKEN: ""

# Set these values for GitHub support.
GITHUB_TOKEN: ""

GITHUB_PROJECTS:
  - tag1: "gh_org/gh_project_name"
  - tag2: "gh_org/gh_project_name"

SERVICENOW_TICKETS_URL: ""
SERVICENOW_KB_URL: ""
SERVICENOW_CR_URL: ""
SERVICENOW_SCR_URL: ""

NAMSTR_URL: ""

# Set these values for LDAP lookup support. Switch _ENABLED to true.
LDAP_HOST: ""
LDAP_PORT: ""
LDAP_BASE_DN: ""
LDAP_BASE_PW: ""
LDAP_SEARCH_DN: ""

# Set these values for Roles Management support. Switch _ENABLED to true.
ROLES_URL: ""
ROLES_USERNAME: ""
ROLES_TOKEN: ""

# Set these values for Devboard lookup support.
DEVBOARD_URL: ""
DEVBOARD_JSON: ""
DEVBOARD_API_USER: ""
DEVBOARD_API_SECRET: ""

# Define where a command is enabled here
GLOBAL:
  Help: true
  Visioneers: true
  LDAP: true
  Host: true
  Roles: true
  Devboard: true
  GitHub: true
  ServiceNowTickets: false
  ServiceNowChangeRequests: false
  ServiceNowStdChangeRequests: false
  Namstr: true

# Define who can access extra details on a command
PRIVATE:
  Help: ["msdiez"]

# To add local configuration for a channel, do the following:
# your-channel-name:
#   "The Command": true/false
#
# If you do not specify a command, it will use the GLOBAL config
