# This value must be set.
SLACK_API_TOKEN: ""

# Set these values for GitHub support.
GITHUB_TOKEN: ""

GITHUB_PROJECTS:
  - tag1: "gh_org/gh_project_name"
  - tag2: "gh_org/gh_project_name"

# Set these values for LDAP lookup support. Switch _ENABLED to true.
LDAP_HOST: ""
LDAP_PORT: ""
LDAP_BASE_DN: ""
LDAP_BASE_PW: ""
LDAP_SEARCH_DN: ""

# Set these values for Roles Management support. Switch _ENABLED to true.
ROLES_URL: ""
ROLES_USERNAME: ""
ROLES_TOKEN: ""

# Set these values for Devboard lookup support.
DEVBOARD_URL: ""
DEVBOARD_JSON: ""
DEVBOARD_API_USER: ""
DEVBOARD_API_SECRET: ""
